import type { Lesson } from "./types";

export const lessons: Lesson[] = [
  {
    id: "diagnostic-initial-1",
    world: "Diagnostic",
    title: "Diagnostic initial : voix de reference",
    domain: "Evaluation VoiceAct",
    category: "Diagnostic",
    emotion: "Controle naturel",
    scenario:
      "Tu lis un texte court qui melange narration, tension et conclusion. Cette prise sert de point de depart pour mesurer ton evolution dans un mois.",
    level: 0,
    xp: 15,
    targetWpm: 130,
    objective: "Evaluer ton rythme, ta clarte, tes pauses et ton expressivite de base.",
    coachTip: "Ne cherche pas a impressionner. Lis proprement, avec intention, pour que VoiceAct mesure ton vrai niveau de depart.",
    focusPoints: ["Voix naturelle", "Pauses propres", "Intention claire"],
    successCriteria: ["Le texte est comprehensible", "Les pauses principales sont audibles", "La voix varie sans surjouer"],
    referenceAudio: { status: "commission_required", title: "Diagnostic naturel VoiceAct", exactText: true },
    segments: [
      {
        text: "Au debut, tout semblait parfaitement normal.",
        pauseAfterMs: 550,
        pace: "steady",
        energy: "medium",
        intonation: "low_flat",
        accelerateWords: ["tout semblait"],
        softerWords: ["Au debut"],
        louderWords: ["normal"],
        emphasis: ["debut", "normal"],
        note: "Pose une base claire et neutre.",
        deliveryCue: "Lis simplement, comme si tu installais une histoire credible.",
      },
      {
        text: "Puis un detail a change l atmosphere de toute la piece.",
        pauseAfterMs: 850,
        pace: "steady",
        energy: "contained",
        intonation: "rise_fall",
        accelerateWords: ["a change"],
        louderWords: ["detail"],
        softerWords: ["atmosphere"],
        emphasis: ["detail", "atmosphere"],
        note: "Fais sentir la bascule sans dramatiser.",
        deliveryCue: "Monte legerement sur detail, puis ralentis sur atmosphere.",
      },
      {
        text: "Et c est exactement la que l histoire commence.",
        pauseAfterMs: 900,
        pace: "slow",
        energy: "contained",
        intonation: "fall",
        accelerateWords: ["exactement la"],
        louderWords: ["commence"],
        emphasis: ["exactement", "commence"],
        note: "Termine avec une promesse nette.",
        deliveryCue: "Descends sur commence pour donner envie d ecouter la suite.",
      },
    ],
  },
  {
    id: "horror-hook-1",
    world: "Monde 1",
    title: "Hook horreur : installer le malaise",
    domain: "Voix off createur",
    category: "Hook",
    emotion: "Peur froide",
    scenario: "Tu ouvres une video courte sur une maison abandonnee. Le spectateur doit sentir le danger avant meme de comprendre.",
    level: 1,
    xp: 20,
    targetWpm: 95,
    objective: "Creer une tension froide sans crier.",
    coachTip: "Lis bas, lentement, puis laisse le silence travailler avant la revelation.",
    focusPoints: ["Voix basse", "Silence avant revelation", "Fin de phrase descendante"],
    successCriteria: ["Le debit reste lent", "La pause principale est audible", "La voix ne monte pas en cri"],
    referenceAudio: { status: "commission_required", title: "Hook horreur VoiceAct", exactText: true },
    segments: [
      {
        text: "Personne n aurait du entrer dans cette maison apres minuit.",
        pauseAfterMs: 800,
        pace: "slow",
        energy: "low",
        intonation: "low_rise",
        softerWords: ["Personne", "cette maison"],
        louderWords: ["minuit"],
        emphasis: ["Personne", "minuit"],
        note: "Installe le lieu et le danger sans reveler trop vite.",
        deliveryCue: "Commence presque comme un secret. Monte tres legerement sur minuit.",
      },
      {
        text: "Pourtant, la camera a continue d enregistrer.",
        pauseAfterMs: 1100,
        pace: "slow",
        energy: "contained",
        intonation: "rise_fall",
        accelerateWords: ["a continue"],
        louderWords: ["Pourtant"],
        softerWords: ["enregistrer"],
        emphasis: ["Pourtant", "camera"],
        note: "Fais sentir que la revelation arrive, puis chute froidement.",
        deliveryCue: "Appuie sur Pourtant, puis laisse tomber la fin comme une preuve inquietante.",
      },
    ],
  },
  {
    id: "documentary-hook-1",
    world: "Monde 1",
    title: "Documentaire : poser une voix credible",
    domain: "Voix off createur",
    category: "Narration",
    emotion: "Gravite calme",
    scenario: "Tu introduis une video d histoire ou de geopolitique. Le public doit croire que chaque mot a ete verifie.",
    level: 1,
    xp: 20,
    targetWpm: 125,
    objective: "Raconter avec gravite, clarte et confiance.",
    coachTip: "Garde une voix posee. Chaque information doit sembler importante, pas dramatisee.",
    focusPoints: ["Articulation nette", "Rythme regulier", "Autorite calme"],
    successCriteria: ["Le debit reste proche de 115 mots/min", "Les mots dates sont accentues", "La fin descend avec assurance"],
    referenceAudio: { status: "commission_required", title: "Narration documentaire VoiceAct", exactText: true },
    segments: [
      {
        text: "En 1961, une decision prise dans une salle fermee",
        pauseAfterMs: 500,
        pace: "steady",
        energy: "medium",
        intonation: "low_flat",
        accelerateWords: ["une decision prise"],
        louderWords: ["1961", "decision"],
        emphasis: ["1961", "decision"],
        note: "Annonce le contexte avec assurance.",
        deliveryCue: "Pose la date comme un repere solide, sans effet dramatique.",
      },
      {
        text: "va changer l equilibre du monde.",
        pauseAfterMs: 900,
        pace: "steady",
        energy: "contained",
        intonation: "fall",
        accelerateWords: ["va changer"],
        louderWords: ["monde"],
        emphasis: ["changer", "monde"],
        note: "Descends sur la fin pour donner du poids.",
        deliveryCue: "Ralentis legerement sur monde pour fermer la promesse.",
      },
    ],
  },
  {
    id: "dubbing-threat-1",
    world: "Monde 2",
    title: "Doublage : menace calme",
    domain: "Doublage cinema",
    category: "Doublage",
    emotion: "Menace controlee",
    scenario: "Un personnage dangereux parle doucement. Il ne cherche pas a impressionner, il sait deja qu il domine.",
    level: 2,
    xp: 25,
    targetWpm: 90,
    objective: "Faire peur par le controle, pas par le volume.",
    coachTip: "La menace doit etre calme. Plus tu cries, moins le personnage semble dangereux.",
    focusPoints: ["Controle du volume", "Pauses lourdes", "Derniers mots plus bas"],
    successCriteria: ["La voix reste stable", "La pause cree la tension", "La fin ressemble a une sentence"],
    referenceAudio: { status: "commission_required", title: "Menace calme VoiceAct", exactText: true },
    segments: [
      {
        text: "Tu peux partir maintenant.",
        pauseAfterMs: 700,
        pace: "slow",
        energy: "low",
        intonation: "low_flat",
        softerWords: ["Tu peux", "maintenant"],
        emphasis: ["partir"],
        note: "Garde la voix stable, comme si tu laissais une chance.",
        deliveryCue: "Ne menace pas encore. Fais semblant d etre raisonnable.",
      },
      {
        text: "Mais si tu reviens, je ne serai plus aussi patient.",
        pauseAfterMs: 1200,
        pace: "slow",
        energy: "contained",
        intonation: "fall",
        accelerateWords: ["Mais si tu"],
        louderWords: ["reviens"],
        softerWords: ["patient"],
        emphasis: ["reviens", "patient"],
        note: "Descends sur la fin. La menace doit tomber comme une sentence.",
        deliveryCue: "Place le vrai danger sur reviens, puis ferme la phrase tres bas.",
      },
    ],
  },
  {
    id: "news-urgency-1",
    world: "Monde 2",
    title: "Actualite : urgence sans panique",
    domain: "Voix off createur",
    category: "Narration",
    emotion: "Urgence maitrisee",
    scenario: "Tu annonces une information importante. Il faut creer de l attention sans donner l impression de dramatiser.",
    level: 2,
    xp: 25,
    targetWpm: 155,
    objective: "Garder de l energie tout en restant credible.",
    coachTip: "Avance plus vite qu un documentaire, mais garde des fins propres et comprehensibles.",
    focusPoints: ["Energie medium", "Articulation", "Relance rapide"],
    successCriteria: ["Le debit est dynamique", "Les pauses sont courtes", "Les mots importants ressortent"],
    referenceAudio: { status: "commission_required", title: "Actualite dynamique VoiceAct", exactText: true },
    segments: [
      {
        text: "Depuis ce matin, une nouvelle decision fait reagir tout le pays.",
        pauseAfterMs: 450,
        pace: "steady",
        energy: "medium",
        intonation: "build",
        accelerateWords: ["une nouvelle decision fait reagir"],
        louderWords: ["ce matin", "pays"],
        emphasis: ["ce matin", "decision"],
        note: "Installe l actualite avec une energie nette.",
        deliveryCue: "Garde le sourire vocal leger, comme une alerte serieuse mais claire.",
      },
      {
        text: "Et ses consequences pourraient arriver plus vite que prevu.",
        pauseAfterMs: 700,
        pace: "steady",
        energy: "medium",
        intonation: "fall",
        accelerateWords: ["pourraient arriver", "vite"],
        louderWords: ["consequences"],
        emphasis: ["consequences", "vite"],
        note: "Termine avec une promesse qui donne envie de rester.",
        deliveryCue: "Marque consequences, puis ralentis sur plus vite que prevu.",
      },
    ],
  },
  {
    id: "sad-scene-1",
    world: "Monde 3",
    title: "Doublage : tristesse retenue",
    domain: "Doublage cinema",
    category: "Emotion",
    emotion: "Tristesse contenue",
    scenario: "Le personnage essaie de ne pas craquer. L emotion doit trembler sous la surface, pas exploser.",
    level: 3,
    xp: 30,
    targetWpm: 90,
    objective: "Faire sentir la douleur sans surjouer.",
    coachTip: "Retiens l emotion. Une voix trop theatrale casse la sincerite.",
    focusPoints: ["Souffle court", "Pauses fragiles", "Volume doux"],
    successCriteria: ["Le rythme reste lent", "La voix varie sans crier", "La derniere phrase se casse legerement"],
    referenceAudio: { status: "commission_required", title: "Tristesse retenue VoiceAct", exactText: true },
    segments: [
      {
        text: "Je pensais vraiment que tu resterais.",
        pauseAfterMs: 900,
        pace: "slow",
        energy: "low",
        intonation: "fall",
        softerWords: ["Je pensais", "resterais"],
        louderWords: ["vraiment"],
        emphasis: ["vraiment", "resterais"],
        note: "Laisse entendre la deception, pas la colere.",
        deliveryCue: "Commence doux. Fais descendre resterais comme une realisation douloureuse.",
      },
      {
        text: "Mais je comprends maintenant.",
        pauseAfterMs: 1000,
        pace: "slow",
        energy: "low",
        intonation: "low_flat",
        softerWords: ["Mais", "maintenant"],
        louderWords: ["comprends"],
        emphasis: ["comprends", "maintenant"],
        note: "La phrase doit sonner comme quelqu un qui abandonne.",
        deliveryCue: "Presque sans energie. Laisse le silence apres la phrase faire le travail.",
      },
    ],
  },
  {
    id: "ad-energy-1",
    world: "Monde 3",
    title: "Voix pub : energie propre",
    domain: "Voix off createur",
    category: "Publicite",
    emotion: "Enthousiasme clair",
    scenario: "Tu presentes une solution utile. Il faut donner envie sans sonner faux ou trop vendeur.",
    level: 3,
    xp: 30,
    targetWpm: 175,
    objective: "Etre dynamique, clair et souriant dans la voix.",
    coachTip: "Souris legerement en lisant. L energie doit etre propre, pas agressive.",
    focusPoints: ["Sourire vocal", "Debit rapide", "Mots benefices accentues"],
    successCriteria: ["Le debit est rapide mais clair", "L energie varie", "La conclusion donne envie d agir"],
    referenceAudio: { status: "commission_required", title: "Publicite dynamique VoiceAct", exactText: true },
    segments: [
      {
        text: "En quelques minutes, tu peux transformer une simple idee",
        pauseAfterMs: 350,
        pace: "fast",
        energy: "high",
        intonation: "rise",
        accelerateWords: ["En quelques minutes", "tu peux transformer"],
        louderWords: ["idee"],
        emphasis: ["quelques minutes", "idee"],
        note: "Donne une sensation de facilite et de mouvement.",
        deliveryCue: "Souris dans la voix et avance franchement.",
      },
      {
        text: "en une voix off qui capte vraiment l attention.",
        pauseAfterMs: 650,
        pace: "fast",
        energy: "high",
        intonation: "rise_fall",
        accelerateWords: ["qui capte vraiment"],
        louderWords: ["voix off", "attention"],
        emphasis: ["voix off", "attention"],
        note: "Termine avec une promesse concrete.",
        deliveryCue: "Monte sur voix off, puis ferme fort sur attention.",
      },
    ],
  },
  {
    id: "siwis-emphasis-1",
    world: "Atelier pro",
    title: "Accentuation : porter le mot moteur",
    domain: "Voix off createur",
    category: "Narration",
    emotion: "Determination maitrisee",
    scenario: "Tu suis une prise professionnelle francaise. Les petits mots avancent vite, tandis que le verbe central porte la conviction.",
    level: 2,
    xp: 30,
    targetWpm: 240,
    objective: "Reproduire une cadence professionnelle non uniforme et une accentuation franche.",
    coachTip: "Ecoute d abord la reference. Le violet accelere ; le mot plus grand porte l intention sans devenir un cri.",
    focusPoints: ["Petits mots rapides", "Accentuation du verbe", "Pauses mesurees"],
    successCriteria: ["Les deux pauses restent proches de la reference", "Reviendrons ressort sans cri", "Les mots violets restent intelligibles"],
    referenceAudio: {
      status: "licensed",
      title: "SIWIS · voix professionnelle francaise",
      localPath: "/references/siwis/emph_book_s01_0001.wav",
      sourceUrl: "https://doi.org/10.7488/ds/1705",
      license: "CC BY 4.0",
      attribution: "Yamagishi, Honnet, Garner et Lazaridis · University of Edinburgh CSTR",
      exactText: true,
    },
    segments: [
      {
        text: "Et qu'il le veuille ou non,",
        pauseAfterMs: 300,
        referenceSpeechDurationMs: 1150,
        referenceWordTimings: [
          { word: "Et", startMs: 170, endMs: 290 },
          { word: "qu'il", startMs: 290, endMs: 540 },
          { word: "le", startMs: 540, endMs: 600 },
          { word: "veuille", startMs: 600, endMs: 860 },
          { word: "ou", startMs: 860, endMs: 900 },
          { word: "non,", startMs: 900, endMs: 1150 },
        ],
        timingSource: "professional_reference",
        pace: "fast",
        energy: "medium",
        intonation: "rise_fall",
        accelerateWords: ["qu'il le", "ou"],
        louderWords: ["non"],
        emphasis: ["non"],
        note: "La concession file rapidement puis se ferme sur non.",
        deliveryCue: "Ne donne pas le meme poids a tous les mots.",
      },
      {
        text: "nous reviendrons vers le nord,",
        pauseAfterMs: 340,
        referenceSpeechDurationMs: 1490,
        referenceWordTimings: [
          { word: "nous", startMs: 0, endMs: 230 },
          { word: "reviendrons", startMs: 230, endMs: 860 },
          { word: "vers", startMs: 860, endMs: 1040 },
          { word: "le", startMs: 1040, endMs: 1130 },
          { word: "nord,", startMs: 1130, endMs: 1490 },
        ],
        timingSource: "professional_reference",
        pace: "build",
        energy: "high",
        intonation: "fall",
        accelerateWords: ["vers le"],
        louderWords: ["reviendrons"],
        emphasis: ["reviendrons"],
        note: "Le verbe central est tenu nettement plus longtemps.",
        deliveryCue: "Porte la conviction sur reviendrons, puis ferme sur nord.",
      },
      {
        text: "c'est-a-dire au pays des honnetes gens.",
        pauseAfterMs: 650,
        referenceSpeechDurationMs: 1510,
        referenceWordTimings: [
          { word: "c'est-a-dire", startMs: 0, endMs: 520 },
          { word: "au", startMs: 520, endMs: 580 },
          { word: "pays", startMs: 580, endMs: 850 },
          { word: "des", startMs: 850, endMs: 1050 },
          { word: "honnetes", startMs: 1050, endMs: 1310 },
          { word: "gens.", startMs: 1310, endMs: 1510 },
        ],
        timingSource: "professional_reference",
        pace: "steady",
        energy: "contained",
        intonation: "fall",
        accelerateWords: ["au"],
        softerWords: ["des"],
        emphasis: ["pays", "honnetes gens"],
        note: "La precision se pose, puis la phrase descend.",
        deliveryCue: "Reste clair sur l incise et termine sans ajouter d emphase.",
      },
    ],
  },
];
